SELECT
    B.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
        FROM BOOK B
        JOIN AUTHOR A
            ON B.AUTHOR_ID = A.AUTHOR_ID
        JOIN BOOK_SALES S
            ON B.BOOK_ID = S.BOOK_ID
        WHERE
            TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
        GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
        ORDER BY AUTHOR_ID, CATEGORY DESC