SELECT A.ITEM_ID, C.ITEM_NAME, C.RARITY FROM ITEM_TREE A
LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
JOIN ITEM_INFO C ON A.ITEM_ID = C.ITEM_ID
WHERE B.ITEM_ID IS NULL
ORDER BY A.ITEM_ID DESC