SELECT 
A.CAR_ID, 
A.CAR_TYPE, 
A.DAILY_FEE * (1 - C.DISCOUNT_RATE / 100) * 30 AS 'FEE'
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
ON A.CAR_TYPE = C.CAR_TYPE 
AND C.DURATION_TYPE = '30일 이상'
WHERE A.CAR_TYPE IN ('세단', 'SUV') 
AND A.CAR_ID NOT IN 
(
SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' 
    AND END_DATE >=  '2022-11-01'
)
AND A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE / 100) >= 500000
AND A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE / 100) < 2000000
ORDER BY 
FEE DESC, 
A.CAR_TYPE ASC, 
A.CAR_ID ASC;