SELECT ID, 
CASE 
WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) * 100 < 25 THEN "LOW"
WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) * 100 < 50 THEN "MEDIUM"
WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) * 100 < 75 THEN "HIGH"
WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) * 100 >= 75 THEN "CRITICAL"
END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC;