SELECT
    USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, 
    USED_GOODS_USER.CITY || ' ' || USED_GOODS_USER.STREET_ADDRESS1 || ' ' || USED_GOODS_USER.STREET_ADDRESS2 AS "전체주소",
    SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8, 4) AS "전화번호"
FROM
    USED_GOODS_BOARD
JOIN
    USED_GOODS_USER ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
GROUP BY
    USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, USED_GOODS_USER.STREET_ADDRESS1, USED_GOODS_USER.STREET_ADDRESS2, USED_GOODS_USER.TLNO, USED_GOODS_USER.CITY
HAVING
    COUNT(USED_GOODS_USER.USER_ID) >= 3
ORDER BY
    USED_GOODS_USER.USER_ID DESC