SELECT 
    TO_CHAR(SALES_DATE, 'YYYY') AS YEAR, 
    TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH, 
    GENDER, 
    COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I
JOIN ONLINE_SALE O ON I.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), GENDER
ORDER BY 
    TO_CHAR(SALES_DATE, 'YYYY'),
    TO_CHAR(SALES_DATE, 'MM'),
    GENDER