-- 코드를 입력하세요
SELECT 
    OUT.ANIMAL_ID, OUT.NAME
    FROM 
        ANIMAL_OUTS OUT
    LEFT JOIN ANIMAL_INS INS
        ON INS.ANIMAL_ID = OUT.ANIMAL_ID
    WHERE 
        INS.ANIMAL_ID IS NULL
    ORDER BY
        OUT.ANIMAL_ID, OUT.NAME;