WITH RECURSIVE CTE AS (
    
    SELECT 
    ID,
    1 AS GENERATION,
    PARENT_ID
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION
    
    SELECT 
    B.ID,
    A.GENERATION + 1,
    B.PARENT_ID
    
    FROM CTE A
    JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
    
) 
SELECT COUNT(*), GENERATION
FROM CTE 
WHERE ID NOT IN (SELECT PARENT_ID FROM CTE WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION