SELECT LEFT.CAR_ID, 
CASE
WHEN RIGHT.CAR_ID IS NULL THEN '대여 가능'
ELSE '대여중'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY LEFT
LEFT JOIN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE TO_DATE('2022-10-16', 'YYYY-MM-DD') 
    BETWEEN START_DATE AND END_DATE
) RIGHT ON LEFT.CAR_ID = RIGHT.CAR_ID
GROUP BY LEFT.CAR_ID, RIGHT.CAR_ID
ORDER BY LEFT.CAR_ID DESC