-- 코드를 입력하세요
SELECT
    FOOD_PRODUCT.PRODUCT_ID, 
    FOOD_PRODUCT.PRODUCT_NAME, 
    SUM(FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT) AS TOTAL_SALES
        FROM FOOD_PRODUCT
        JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
        WHERE FOOD_ORDER.PRODUCE_DATE >= '2022-05-01'
        AND FOOD_ORDER.PRODUCE_DATE < '2022-06-01'
        GROUP BY PRODUCT_ID
            ORDER BY TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_ID ASC