SELECT
    H.FLAVOR
    FROM
        FIRST_HALF H
    JOIN 
        JULY J ON H.FLAVOR = J.FLAVOR
    GROUP BY 
        H.FLAVOR
    ORDER BY
        SUM(H.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
    FETCH FIRST 3 ROWS ONLY;