SELECT
    AP.APNT_NO, PA.PT_NAME, PA.PT_NO, DOC.MCDP_CD, DOC.DR_NAME, AP.APNT_YMD
FROM
    APPOINTMENT AP
JOIN 
    PATIENT PA ON AP.PT_NO = PA.PT_NO
JOIN 
    DOCTOR DOC ON AP.MDDR_ID = DOC.DR_ID
WHERE
    TO_CHAR(APNT_YMD, 'YYYY-MM-DD') = '2022-04-13' AND
    DOC.MCDP_CD = 'CS' AND
    AP.APNT_CNCL_YN = 'N'
ORDER BY
    APNT_YMD ASC