SELECT EM.EMP_NO, EM.EMP_NAME,
    CASE 
        WHEN AVG(GR.SCORE) >= 96 THEN 'S'
        WHEN AVG(GR.SCORE) >= 90 THEN 'A'
        WHEN AVG(GR.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN AVG(GR.SCORE) >= 96 THEN EM.SAL * 0.2
        WHEN AVG(GR.SCORE) >= 90 THEN EM.SAL * 0.15
        WHEN AVG(GR.SCORE) >= 80 THEN EM.SAL * 0.10
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES EM
JOIN HR_DEPARTMENT DE ON EM.DEPT_ID = DE.DEPT_ID
JOIN HR_GRADE GR ON EM.EMP_NO = GR.EMP_NO
GROUP BY EM.EMP_NO, EM.EMP_NAME, EM.SAL