SELECT
    CASE
        WHEN SUBSTR(TO_CHAR(DATETIME, 'HH24'), 1, 1) = '0' THEN SUBSTR(TO_CHAR(DATETIME, 'HH24'), 2)
        ELSE TO_CHAR(DATETIME, 'HH24') 
    END AS HOUR,
    COUNT(*) AS COUNT
FROM
    ANIMAL_OUTS
WHERE
    TO_CHAR(DATETIME, 'HH24') >= 9 AND TO_CHAR(DATETIME,'HH24') < 20
GROUP BY
    TO_CHAR(DATETIME, 'HH24')
ORDER BY
    TO_CHAR(DATETIME, 'HH24') ASC