SELECT
    TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN

    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)
    
GROUP BY
    TO_CHAR(START_DATE, 'MM'), CAR_ID
HAVING 
    COUNT(*) > 0 AND TO_CHAR(START_DATE, 'MM') BETWEEN 08 AND 10
ORDER BY
    MONTH ASC, CAR_ID DESC