SELECT
    CAR_RENTAL_COMPANY_CAR.CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY 
            ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
            WHERE CAR_RENTAL_COMPANY_CAR.CAR_TYPE = '세단'
            AND CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD')
            AND CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
                 GROUP BY CAR_RENTAL_COMPANY_CAR.CAR_ID
                 ORDER BY CAR_RENTAL_COMPANY_CAR.CAR_ID DESC