SELECT FISH_INFO.ID, FISH_NAME_INFO.FISH_NAME, FISH_INFO.LENGTH
FROM FISH_INFO
JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_LENGTHS ON FISH_INFO.FISH_TYPE = MAX_LENGTHS.FISH_TYPE AND FISH_INFO.LENGTH = MAX_LENGTHS.MAX_LENGTH
ORDER BY FISH_INFO.ID ASC