SELECT
    BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
        FROM BOOK
        WHERE CATEGORY = '인문' 
        AND TO_DATE('2021-01-01', 'YYYY-MM-DD') <= PUBLISHED_DATE 
        AND PUBLISHED_DATE <= TO_DATE('2021-12-31', 'YYYY-MM-DD')
            ORDER BY PUBLISHED_DATE ASC