SELECT
    ICECREAM_INFO.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF
JOIN ICECREAM_INFO
    ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
GROUP BY
    ICECREAM_INFO.INGREDIENT_TYPE