-- 코드를 작성해주세요
SELECT 
    DEPT.DEPT_ID, DEPT.DEPT_NAME_EN, ROUND(AVG(HR.SAL),0) AS AVG_SAL
FROM   
    HR_DEPARTMENT DEPT
JOIN
    HR_EMPLOYEES HR ON DEPT.DEPT_ID = HR.DEPT_ID
GROUP BY 
    HR.DEPT_ID
ORDER BY
    AVG_SAL DESC